import { CardInfo } from "../../types/common/CardInfo";
import { CardNames } from "../../types/common/CardNames";
import { CardTypes } from "../../types/common/CardTypes";
import { CardMonths } from "../../types/common/CardMonths";
import { CardPlants } from "../../types/common/CardPlants";

const CARD_INFO_ARR: CardInfo[] = [
  {
    name: CardNames.松,
    type: CardTypes.カス,
    month: CardMonths.January,
    plant: CardPlants.松,
  },
  {
    name: CardNames.松,
    type: CardTypes.カス,
    month: CardMonths.January,
    plant: CardPlants.松,
  },
  {
    name: CardNames.松に赤短,
    type: CardTypes.短冊,
    month: CardMonths.January,
    plant: CardPlants.松,
  },
  {
    name: CardNames.松に鶴,
    type: CardTypes.光札,
    month: CardMonths.January,
    plant: CardPlants.松,
  },
  {
    name: CardNames.梅,
    type: CardTypes.カス,
    month: CardMonths.February,
    plant: CardPlants.梅,
  },
  {
    name: CardNames.梅,
    type: CardTypes.カス,
    month: CardMonths.February,
    plant: CardPlants.梅,
  },
  {
    name: CardNames.梅に赤短,
    type: CardTypes.カス,
    month: CardMonths.February,
    plant: CardPlants.梅,
  },
  {
    name: CardNames.梅に鴬,
    type: CardTypes.種札,
    month: CardMonths.February,
    plant: CardPlants.梅,
  },
  {
    name: CardNames.桜,
    type: CardTypes.カス,
    month: CardMonths.March,
    plant: CardPlants.桜,
  },
  {
    name: CardNames.桜,
    type: CardTypes.カス,
    month: CardMonths.March,
    plant: CardPlants.桜,
  },
  {
    name: CardNames.桜に赤短,
    type: CardTypes.短冊,
    month: CardMonths.March,
    plant: CardPlants.桜,
  },
  {
    name: CardNames.満開の桜に幔幕,
    type: CardTypes.光札,
    month: CardMonths.March,
    plant: CardPlants.桜,
  },
  {
    name: CardNames.藤,
    type: CardTypes.カス,
    month: CardMonths.April,
    plant: CardPlants.藤,
  },
  {
    name: CardNames.藤,
    type: CardTypes.カス,
    month: CardMonths.April,
    plant: CardPlants.藤,
  },
  {
    name: CardNames.藤に短冊,
    type: CardTypes.短冊,
    month: CardMonths.April,
    plant: CardPlants.藤,
  },
  {
    name: CardNames.藤に時鳥,
    type: CardTypes.光札,
    month: CardMonths.April,
    plant: CardPlants.藤,
  },
  {
    name: CardNames.杜若,
    type: CardTypes.カス,
    month: CardMonths.May,
    plant: CardPlants.杜若,
  },
  {
    name: CardNames.杜若,
    type: CardTypes.カス,
    month: CardMonths.May,
    plant: CardPlants.杜若,
  },
  {
    name: CardNames.杜若に短冊,
    type: CardTypes.短冊,
    month: CardMonths.May,
    plant: CardPlants.杜若,
  },
  {
    name: CardNames.杜若に八橋,
    type: CardTypes.種札,
    month: CardMonths.May,
    plant: CardPlants.杜若,
  },
  {
    name: CardNames.牡丹,
    type: CardTypes.カス,
    month: CardMonths.June,
    plant: CardPlants.牡丹,
  },
  {
    name: CardNames.牡丹,
    type: CardTypes.カス,
    month: CardMonths.June,
    plant: CardPlants.牡丹,
  },
  {
    name: CardNames.牡丹に青短,
    type: CardTypes.短冊,
    month: CardMonths.June,
    plant: CardPlants.牡丹,
  },
  {
    name: CardNames.花王に蝶,
    type: CardTypes.種札,
    month: CardMonths.June,
    plant: CardPlants.牡丹,
  },
  {
    name: CardNames.萩,
    type: CardTypes.カス,
    month: CardMonths.July,
    plant: CardPlants.萩,
  },
  {
    name: CardNames.萩,
    type: CardTypes.カス,
    month: CardMonths.July,
    plant: CardPlants.萩,
  },
  {
    name: CardNames.萩に短冊,
    type: CardTypes.短冊,
    month: CardMonths.July,
    plant: CardPlants.萩,
  },
  {
    name: CardNames.山萩に山猪,
    type: CardTypes.種札,
    month: CardMonths.July,
    plant: CardPlants.萩,
  },
  {
    name: CardNames.芒,
    type: CardTypes.カス,
    month: CardMonths.August,
    plant: CardPlants.芒,
  },
  {
    name: CardNames.芒,
    type: CardTypes.カス,
    month: CardMonths.August,
    plant: CardPlants.芒,
  },
  {
    name: CardNames.芒に雁,
    type: CardTypes.種札,
    month: CardMonths.August,
    plant: CardPlants.芒,
  },
  {
    name: CardNames.芒に望月,
    type: CardTypes.光札,
    month: CardMonths.August,
    plant: CardPlants.芒,
  },
  {
    name: CardNames.菊,
    type: CardTypes.カス,
    month: CardMonths.September,
    plant: CardPlants.菊,
  },
  {
    name: CardNames.菊,
    type: CardTypes.カス,
    month: CardMonths.September,
    plant: CardPlants.菊,
  },
  {
    name: CardNames.菊に青短,
    type: CardTypes.短冊,
    month: CardMonths.September,
    plant: CardPlants.菊,
  },
  {
    name: CardNames.菊に盃,
    type: CardTypes.種札,
    month: CardMonths.September,
    plant: CardPlants.菊,
  },
  {
    name: CardNames.紅葉,
    type: CardTypes.カス,
    month: CardMonths.October,
    plant: CardPlants.紅葉,
  },
  {
    name: CardNames.紅葉,
    type: CardTypes.カス,
    month: CardMonths.October,
    plant: CardPlants.紅葉,
  },
  {
    name: CardNames.紅葉に青短,
    type: CardTypes.短冊,
    month: CardMonths.October,
    plant: CardPlants.紅葉,
  },
  {
    name: CardNames.楓に鹿,
    type: CardTypes.種札,
    month: CardMonths.October,
    plant: CardPlants.紅葉,
  },
  {
    name: CardNames.柳,
    type: CardTypes.カス,
    month: CardMonths.November,
    plant: CardPlants.柳,
  },
  {
    name: CardNames.柳に短冊,
    type: CardTypes.短冊,
    month: CardMonths.November,
    plant: CardPlants.柳,
  },
  {
    name: CardNames.柳に燕,
    type: CardTypes.種札,
    month: CardMonths.November,
    plant: CardPlants.柳,
  },
  {
    name: CardNames.柳に小野道風,
    type: CardTypes.光札,
    month: CardMonths.November,
    plant: CardPlants.柳,
  },
  {
    name: CardNames.桐,
    type: CardTypes.カス,
    month: CardMonths.December,
    plant: CardPlants.桐,
  },
  {
    name: CardNames.桐,
    type: CardTypes.カス,
    month: CardMonths.December,
    plant: CardPlants.桐,
  },
  {
    name: CardNames.桐色違い,
    type: CardTypes.カス,
    month: CardMonths.December,
    plant: CardPlants.桐,
  },
  {
    name: CardNames.五桐に鳳凰,
    type: CardTypes.光札,
    month: CardMonths.December,
    plant: CardPlants.桐,
  },
];

export { CARD_INFO_ARR };
