import { CardNames } from "../../types/common/CardNames";

const CARD_IMAGES_MAP: Map<CardNames, string> = new Map<CardNames, string>([
  [CardNames.松に鶴, "../assets/images/hanahuda-1-1.jpg"],
  [CardNames.松に赤短, "../assets/images/hanahuda-1-2.jpg"],
  [CardNames.松, "../assets/images/hanahuda-1-3.jpg"],
  [CardNames.松, "../assets/images/hanahuda-1-4.jpg"],
  [CardNames.梅に鴬, "../assets/images/hanahuda-2-1.jpg"],
  [CardNames.梅に赤短, "../assets/images/hanahuda-2-2.jpg"],
  [CardNames.梅, "../assets/images/hanahuda-2-3.jpg"],
  [CardNames.梅, "../assets/images/hanahuda-2-4.jpg"],
  [CardNames.満開の桜に幔幕, "../assets/images/hanahuda-3-1.jpg"],
  [CardNames.桜に赤短, "../assets/images/hanahuda-3-2.jpg"],
  [CardNames.桜, "../assets/images/hanahuda-3-3.jpg"],
  [CardNames.桜, "../assets/images/hanahuda-3-4.jpg"],
  [CardNames.藤に時鳥, "../assets/images/hanahuda-4-1.jpg"],
  [CardNames.藤に短冊, "../assets/images/hanahuda-4-2.jpg"],
  [CardNames.藤, "../assets/images/hanahuda-4-3.jpg"],
  [CardNames.藤, "../assets/images/hanahuda-4-4.jpg"],
  [CardNames.杜若に八橋, "../assets/images/hanahuda-5-1.jpg"],
  [CardNames.杜若に短冊, "../assets/images/hanahuda-5-2.jpg"],
  [CardNames.杜若, "../assets/images/hanahuda-5-3.jpg"],
  [CardNames.杜若, "../assets/images/hanahuda-5-4.jpg"],
  [CardNames.花王に蝶, "../assets/images/hanahuda-6-1.jpg"],
  [CardNames.牡丹に青短, "../assets/images/hanahuda-6-2.jpg"],
  [CardNames.牡丹, "../assets/images/hanahuda-6-3.jpg"],
  [CardNames.牡丹, "../assets/images/hanahuda-6-4.jpg"],
  [CardNames.山萩に山猪, "../assets/images/hanahuda-7-1.jpg"],
  [CardNames.萩に短冊, "../assets/images/hanahuda-7-2.jpg"],
  [CardNames.萩, "../assets/images/hanahuda-7-3.jpg"],
  [CardNames.萩, "../assets/images/hanahuda-7-4.jpg"],
  [CardNames.芒に望月, "../assets/images/hanahuda-8-1.jpg"],
  [CardNames.芒に雁, "../assets/images/hanahuda-8-2.jpg"],
  [CardNames.芒, "../assets/images/hanahuda-8-3.jpg"],
  [CardNames.芒, "../assets/images/hanahuda-8-4.jpg"],
  [CardNames.菊に盃, "../assets/images/hanahuda-9-1.jpg"],
  [CardNames.菊に青短, "../assets/images/hanahuda-9-2.jpg"],
  [CardNames.菊, "../assets/images/hanahuda-9-3.jpg"],
  [CardNames.菊, "../assets/images/hanahuda-9-4.jpg"],
  [CardNames.楓に鹿, "../assets/images/hanahuda-10-1.jpg"],
  [CardNames.紅葉に青短, "../assets/images/hanahuda-10-2.jpg"],
  [CardNames.紅葉, "../assets/images/hanahuda-10-3.jpg"],
  [CardNames.紅葉, "../assets/images/hanahuda-10-4.jpg"],
  [CardNames.柳に小野道風, "../assets/images/hanahuda-11-1.jpg"],
  [CardNames.柳に燕, "../assets/images/hanahuda-11-2.jpg"],
  [CardNames.柳に短冊, "../assets/images/hanahuda-11-3.jpg"],
  [CardNames.柳, "../assets/images/hanahuda-11-4.jpg"],
  [CardNames.五桐に鳳凰, "../assets/images/hanahuda-12-1.jpg"],
  [CardNames.桐色違い, "../assets/images/hanahuda-12-4.jpg"],
  [CardNames.桐, "../assets/images/hanahuda-12-3.jpg"],
  [CardNames.桐, "../assets/images/hanahuda-12-4.jpg"],
]);

export { CARD_IMAGES_MAP };
